# Generated by Django 3.2.25 on 2025-06-17 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_agua', models.CharField(max_length=10)),
                ('capacidad_litros', models.IntegerField()),
                ('peces', models.TextField()),
                ('fecha_ultimo_mantenimiento', models.DateTimeField(blank=True, null=True)),
                ('iluminacion_led', models.BooleanField(default=False)),
                ('observaciones', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
